"""add two kolumns

Revision ID: bb5e44f04f5f
Revises: b34d5d438aa1
Create Date: 2025-01-10 23:55:12.152570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5e44f04f5f'
down_revision: Union[str, None] = 'b34d5d438aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=False))
    op.add_column('users', sa.Column('telegram_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_id')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
