"""five

Revision ID: 0275927c32e2
Revises: 58c1b51b1ae7
Create Date: 2025-01-24 17:54:26.147640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0275927c32e2'
down_revision: Union[str, None] = '58c1b51b1ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('chat_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'message', 'chat', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'chat_id')
    # ### end Alembic commands ###
