version: "3"

services:

  fast-api:
    build:
      context: ./api
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    networks:
      - dev

#  fast-api-comands:
#    build:
#      context: ./api
#      dockerfile: docker/dev/Dockerfile
#    volumes:
#      - ./api:/app
#    networks:
#      - dev
#    user: "1000:1000"


  db-postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: user
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - dev
    ports:
      - "5432:5432"


networks:
  dev:

volumes:
  uploads:
  db-volume:
    driver: local
