version: "3"

services:

  fast-api:
    build:
      context: ./api
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    networks:
      - dev
    environment:
      UPLOAD_DIR: uploads
      SMS_SERVICE_KEY: VJE190N841KGED5V624GD9EOFOB7XG89D819V56O1Y6B29P6I59792X991OGYY49
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: user

  bot:
    build:
      context: ./bot
      dockerfile: docker/Dockerfile
    volumes:
      - ./bot:/app
    networks:
      - dev

  db-postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: user
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - dev
    ports:
      - "5432:5432"


  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dev

networks:
  dev:

volumes:
  redis_data:
  uploads:
  db-volume:
    driver: local
