import os


UPLOAD_DIR = os.getenv('UPLOAD_DIR')
SMS_SERVICE_KEY = os.getenv('SMS_SERVICE_KEY')
POSTGRES_USER = os.getenv('POSTGRES_USER')
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD')
POSTGRES_DB = os.getenv('POSTGRES_DB')
JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY')
RABBIT_URL = os.getenv('RABBIT_URL')
